# Generated by Django 4.0.5 on 2022-08-07 11:55

import bboard.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(bboard.models.get_min_length)], verbose_name='Имя')),
                ('second_name', models.CharField(default='', max_length=15, validators=[django.core.validators.MinLengthValidator(bboard.models.get_min_length)], verbose_name='Второе имя')),
                ('skin_color', models.CharField(blank=True, default='', max_length=15, null=True, validators=[django.core.validators.MinLengthValidator(bboard.models.get_min_length)], verbose_name='Цвет кожи')),
                ('sex', models.CharField(choices=[('M', 'Женщина'), ('F', 'Мужчина'), ('N', 'Неопределенный')], max_length=1, verbose_name='Пол')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('mail', models.EmailField(default=' ', max_length=30, validators=[django.core.validators.EmailValidator(message='Некорректный ввод')], verbose_name='Почта')),
                ('git', models.URLField(blank=True, default=' ', max_length=90, null=True, validators=[django.core.validators.URLValidator(code='invalid', message='Введите корректный Git адрес', regex='github.com', schemes=None)], verbose_name='Ссылка на Git')),
            ],
            options={
                'verbose_name': 'Человек',
                'verbose_name_plural': 'Люди',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Рубрика',
                'verbose_name_plural': 'Рубрики',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FirstModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Товар')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Цена')),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Опубликовано')),
                ('rubric', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_query_name='FMfilter', to='bboard.rubric', verbose_name='Рубрика')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
                'ordering': ['-rubric'],
                'get_latest_by': 'published',
            },
        ),
    ]
