# Generated by Django 4.0.5 on 2022-07-04 13:24

import bboard.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('bboard', '0001_initial'), ('bboard', '0002_alter_firstmodel_content_alter_firstmodel_price_and_more'), ('bboard', '0003_rubric_alter_firstmodel_options_firstmodel_rubric'), ('bboard', '0004_person'), ('bboard', '0005_person_mail_alter_person_age_alter_person_name_and_more'), ('bboard', '0006_person_git_alter_person_mail'), ('bboard', '0007_alter_person_git'), ('bboard', '0008_person_birth_date')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Рубрика',
                'verbose_name_plural': 'Рубрики',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FirstModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Товар')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Цена')),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Опубликовано')),
                ('rubric', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='bboard.rubric', verbose_name='Рубрика')),
            ],
            options={
                'ordering': ['-published'],
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(bboard.models.get_min_length)], verbose_name='Имя')),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='Пол')),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(bboard.models.get_min_age, message='Регистрация доступна пользователям с 18 лет')], verbose_name='Возраст')),
                ('mail', models.EmailField(default=' ', max_length=30, validators=[django.core.validators.EmailValidator(message='некорректный ввод')], verbose_name='Почта')),
                ('git', models.URLField(default=' ', max_length=90, validators=[django.core.validators.URLValidator(code='607', message='Введите корректный Git адрес', regex='github.com', schemes=None)], verbose_name='Ссылка на Git')),
                ('birth_date', models.DateField(default='2022-07-02', verbose_name='Дата рождения')),
            ],
            options={
                'verbose_name': 'Человек',
                'verbose_name_plural': 'Люди',
                'ordering': ['name'],
            },
        ),
    ]
