# Generated by Django 4.1 on 2022-08-16 08:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubric',
            name='name',
            field=models.CharField(db_index=True, max_length=30, validators=[django.core.validators.MinLengthValidator(2, message='Название слишком короткое!')], verbose_name='Название'),
        ),
    ]
