# Generated by Django 4.0.5 on 2022-07-04 13:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0001_squashed_0008_person_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='git',
            field=models.URLField(default=' ', max_length=90, validators=[django.core.validators.URLValidator(code='invalid', message='Введите корректный Git адрес', regex='github.com', schemes=None)], verbose_name='Ссылка на Git'),
        ),
        migrations.AlterField(
            model_name='person',
            name='mail',
            field=models.EmailField(default=' ', max_length=30, validators=[django.core.validators.EmailValidator(message='Некорректный ввод')], verbose_name='Почта'),
        ),
    ]
