# Generated by Django 4.0.5 on 2022-07-08 10:38

import bboard.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0002_alter_person_git_alter_person_mail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='firstmodel',
            options={'get_latest_by': 'published', 'ordering': ['-published'], 'verbose_name': 'Объявление', 'verbose_name_plural': 'Объявления'},
        ),
        migrations.AddField(
            model_name='person',
            name='second_name',
            field=models.CharField(default=' ', max_length=15, validators=[django.core.validators.MinLengthValidator(bboard.models.get_min_length)], verbose_name='Второе имя'),
        ),
        migrations.AddField(
            model_name='person',
            name='skin_color',
            field=models.CharField(default=' ', max_length=15, validators=[django.core.validators.MinLengthValidator(bboard.models.get_min_length)], verbose_name='Цвет кожи'),
        ),
        migrations.AlterField(
            model_name='firstmodel',
            name='rubric',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_query_name='FMfilter', to='bboard.rubric', verbose_name='Рубрика'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(bboard.models.get_min_length)], verbose_name='Имя'),
        ),
    ]
