# Generated by Django 4.1 on 2022-08-28 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0002_alter_rubric_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubric',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_query_name='Pfilter', to='bboard.person', verbose_name='Собственник'),
        ),
    ]
