# Generated by Django 4.0.5 on 2022-07-02 10:56

import bboard.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0004_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='mail',
            field=models.EmailField(default='mail@mail.com', max_length=15, validators=[django.core.validators.EmailValidator(message='некорректный ввод')], verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(bboard.models.get_min_age, message='Регистрация доступна пользователям с 18 лет')], verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(bboard.models.get_min_length)], verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='person',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='Пол'),
        ),
    ]
