# Generated by Django 4.0.5 on 2022-08-03 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0004_alter_person_second_name_alter_person_skin_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='firstmodel',
            options={'get_latest_by': 'published', 'ordering': ['-rubric'], 'verbose_name': 'Объявление', 'verbose_name_plural': 'Объявления'},
        ),
    ]
