# Generated by Django 4.1 on 2022-08-29 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0004_spare_machine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bboard.machine')),
                ('spare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bboard.spare')),
            ],
        ),
    ]
