# Generated by Django 4.1 on 2022-08-29 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0005_kit'),
    ]

    operations = [
    ]
