# Generated by Django 4.0.5 on 2022-07-02 11:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0005_person_mail_alter_person_age_alter_person_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='git',
            field=models.URLField(default=' ', max_length=30, validators=[django.core.validators.URLValidator(code='607', message='Введите корректный Git адрес', regex='github.com', schemes=None)], verbose_name='Ссылка на Git'),
        ),
        migrations.AlterField(
            model_name='person',
            name='mail',
            field=models.EmailField(default=' ', max_length=30, validators=[django.core.validators.EmailValidator(message='некорректный ввод')], verbose_name='Почта'),
        ),
    ]
