# Generated by Django 4.0.5 on 2022-07-02 13:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0006_person_git_alter_person_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='git',
            field=models.URLField(default=' ', max_length=90, validators=[django.core.validators.URLValidator(code='607', message='Введите корректный Git адрес', regex='github.com', schemes=None)], verbose_name='Ссылка на Git'),
        ),
    ]
