# Generated by Django 4.0.5 on 2022-07-02 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0007_alter_person_git'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='birth_date',
            field=models.DateField(default='2022-07-02', verbose_name='Дата рождения'),
        ),
    ]
