# Generated by Django 4.1 on 2022-08-29 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0007_remove_machine_spares'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='spares',
            field=models.ManyToManyField(through='bboard.Kit', to='bboard.spare'),
        ),
    ]
