# Generated by Django 4.1 on 2022-08-30 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0011_privatemessage_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privatemessage',
            name='message',
        ),
    ]
