# Generated by Django 4.1 on 2022-08-30 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0012_remove_privatemessage_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatemessage',
            name='message',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='bboard.message'),
            preserve_default=False,
        ),
    ]
