# Generated by Django 4.1 on 2022-08-30 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0013_privatemessage_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privatemessage',
            name='id',
        ),
        migrations.AlterField(
            model_name='privatemessage',
            name='message',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bboard.message'),
        ),
    ]
