# Generated by Django 4.0.5 on 2022-06-28 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelForWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Услуга')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Цена')),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Опубликовано')),
                ('field_name', models.Field(help_text='Текст безвозмездной помощи')),
                ('email', models.EmailField(max_length=30, verbose_name='Почта')),
                ('urlf', models.URLField(max_length=30, verbose_name='URL адрес')),
                ('boolf', models.BooleanField(null=True)),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['-title'],
            },
        ),
    ]
